[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

# Redirecionamento obrigatório para que React Router funcione na Netlify
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
