export const pikaraokeScoreReviews = {
  low: [
    "{name}, essa foi… uma experiência sonora única.",
    "{name}, o importante é que você foi com coragem!",
    "{name}, hoje o microfone saiu traumatizado.",
    "{name}, já ouvi melhor… mas já ouvi pior também.",
    "{name}, isso foi ousado. Vamos chamar de arte!",
    "{name}, respira, toma água e tenta de novo!",
    "{name}, a plateia tá viva — isso já é vitória.",
    "{name}, manda mais baixo… ou mais alto… ou diferente… 😂",
    "{name}, você tentou. E isso conta pontos!",
  ],
  mid: [
    "{name}, foi bom! Não perfeito, mas bom!",
    "Boa, {name}! Já dá pra encarar o palco.",
    "{name}, curti! Só faltou um tiquinho de confiança.",
    "{name}, tá no caminho: mais uma e você decola.",
    "Ok {name}! Agora é só repetir isso com mais força!",
    "{name}, a galera aprovou! (com carinho)",
    "{name}, isso foi decente! E decente aqui é elogio.",
    "Tá melhorando, {name}! Continua que vai.",
    "{name}, terminou em pé — sucesso!",
  ],
  good: [
    "{name}, mandou bem demais! 👏",
    "Boa, {name}! A galera curtiu!",
    "{name}, isso foi muito bom — digno de replay!",
    "{name}, tá cantando bonito!",
    "Show, {name}! Soltou a voz!",
    "{name}, você tá ficando perigoso(a) no karaokê! 😄",
    "Boa, {name}! Agora é só manter esse nível.",
    "{name}, afinação on. Carisma on. Sucesso!",
    "{name}, você nasceu pra noite de karaokê!",
    "{name}, parabéns! Foi muito bom mesmo!",
    "{name}, tá voando! 🚀",
    "{name}, a plateia pediu bis!",
  ],
  high: [
    "Parabéns {name}! Isso foi INCRÍVEL!",
    "Uau {name}… você treina escondido(a), né?",
    "{name}, por favor, cante mais uma! (sério)",
    "{name}, você arrasa! Isso foi nível show!",
    "Eita! Que talento, {name}!",
    "{name}, isso sim é performance!",
    "{name}, você nasceu pra isso!",
    "A plateia foi à loucura com {name}!",
    "{name} mitou! 🔥",
    "Simplesmente {name}. Icônico(a)!",
  ],
  almostPerfect: [
    "{name}, isso foi QUASE perfeito! Impressionante! 🌟",
    "99 pontos?! {name}, você é uma lenda!",
    "{name}, faltou UM pontinho pro 100! Que show!",
    "A perfeição passou perto, {name}! Incrível!",
    "{name}, 99! Você tá no hall da fama! 🏅",
    "Isso foi épico, {name}! 99 pontos merece respeito!",
    "{name}, quase lá! A próxima é o 100! 💪",
  ],
  perfect: [
    "🏆 {name} TIROU 100!!! LENDÁRIO!!! 🏆",
    "100 PONTOS! {name}, você é PERFEITO(A)! 👑",
    "{name}, ISSO É HISTÓRICO! 100 PONTOS! 🎉",
    "INACREDITÁVEL! {name} alcançou a PERFEIÇÃO! ⭐",
    "🔥 {name} DESTRUIU! 100 PONTOS! GOAT! 🔥",
    "O MICROFONE SE CURVA DIANTE DE {name}! 100! 🎤👑",
    "{name}, VOCÊ É O(A) MAIOR! 100 PONTOS! HISTÓRICO!",
    "CHAMEM A RECORD! {name} FEZ 100 PONTOS! 📺🏆",
  ],
} as const;
